# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-09 11:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesforceCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('oauth_id', models.CharField(blank=True, max_length=255, null=True)),
                ('oauth_id_token', models.CharField(blank=True, max_length=1200, null=True)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('token_type', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xero_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
