# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 18:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesforce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesforceQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(choices=[('OP', 'Opportunity')], max_length=2)),
            ],
        ),
        migrations.RenameField(
            model_name='salesforcecredential',
            old_name='oauth_id_token',
            new_name='id_token',
        ),
        migrations.RenameField(
            model_name='salesforcecredential',
            old_name='oauth_id',
            new_name='id_url',
        ),
        migrations.RenameField(
            model_name='salesforcecredential',
            old_name='token',
            new_name='instance_url',
        ),
        migrations.AddField(
            model_name='salesforcecredential',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesforcecredential',
            name='scope',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='salesforcecredential',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesforce_credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesforcequery',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salesforce.SalesforceCredential'),
        ),
    ]
